org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.projectcachedir=/Volumes/256G/AndroidDev/app3-android-build/project-cache
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.project.persistent.dir=/Volumes/256G/AndroidDev/app3-android-build/kotlin-project-data
kotlin.project.persistent.dir.gradle.disableWrite=true
app3.android.buildRoot=/Volumes/256G/AndroidDev/app3-android-build
android.uniquePackageNames=false
android.r8.strictFullModeForKeepRules=false
